[project]
name = "qml"
version = "0.1.0"
description = "Resources for quantum machine learning research"
readme = "README.md"
authors = [
    { name = "Rory Arden Linerud", email = "roryarden@icloud.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
qml = "qml:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
